#!/usr/bin/ansible-playbook
---
- name: Install, enable and  start node_explorer agent on CentOS 7 
  hosts: wk8s-node2 
  become: yes
  
  tasks:
    - name        : install epel repo
      yum         : name=epel-release


# node_exporter block

    - name        : download node_exporter 
      unarchive   : 
        src       : https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        dest      : ./
        remote_src: yes 

    - name        : copy to /usr/sbin
      copy        :
        remote_src: 1
        src       : ./node_exporter-1.3.1.linux-amd64/node_exporter
        dest      : /usr/sbin/node_exporter
    
    - name         : add user node_exporter
      user         :
        name       : node_exporter
        shell      : /usr/bin/false
        system     : 1
        state      : present
        create_home: 0
   
    - name        : copy service file to systemd
      copy        :
        src       : ./node_exporter.service
        dest      : /etc/systemd/system/node_exporter.service

    - name            : start enable and start node_exporter.service
      systemd         :
        daemon_reload : 1
        name          : node_exporter
        enabled       : 1
        state         : started


#    - name   :
#     
#    - name   : install nginx
#      yum    : name=nginx update_cache=yes
#
#    - name   : create conf.d directory
#      file   :
#        path : /etc/nginx/conf.d      
#        state: directory
#        mode : '0755' 
#
#    - name   : copy nginx config file
#      template: 
#        src  : '{{ source_file  }}'
#        dest : '{{ conf_file }}'
#      notify : restart nginx
#
#    - name   : create dir for tls
#      file   : 
#        path : /etc/nginx/certs
#        state: directory
#        mode : '0755' 
#
#    - name   : copy tls key
#      copy   : src=keys/https.key dest={{ tls_key_file }} owner=root mode=0600
#      notify : restart nginx
#
#    - name   : copy tls certificate
#      copy   : src=keys/https.cert dest={{ tls_cert_file }} owner=root mode=0600
#      notify : restart nginx
#
#    - name   : copy index.html
#      template:
#        src  : templates/index.html.j2
#        dest : /usr/share/nginx/html/index.html
#        mode : 0644
#
#    - name   : start nginx
#      service:
#        name : nginx
#        state: started
#        enabled: 1
#
#  handlers   :
#    - name   : restart nginx
#      service: name=nginx state=restarted 
#  roles:
#    - nginx_on_centos
...
