#!/usr/bin/ansible-playbook --ask-vault-pass


name: Configure web server with nginx
  hosts: e6432 
  become: yes
  
  vars:
    source_file          : ./templates/nginx-tls.conf.j2
    conf_file            : /etc/nginx/conf.d/https.conf
    tls_cert_file        : /etc/nginx/certs/https.cert
    tls_key_file         : /etc/nginx/certs/https.key
    remote_password      : !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32653630396538373336306662386135363730376536356638656137666333366262653839653636
          6463363564666533333166636464313035633536663737330a666639313630646333633165323730
          34313163363037306139626165346237356138666638666162356138333833353038636431353336
          3235336463373034300a666330383162353136626664393633643834646130653132303262356237
          3138

  tasks:
    - name   : install epel repo
      yum    : name=epel-release


    - name   :
     
    - name   : install nginx
      yum    : name=nginx update_cache=yes

    - name   : create conf.d directory
      file   :
        path : /etc/nginx/conf.d      
        state: directory
        mode : '0755' 

    - name   : copy nginx config file
      template: 
        src  : '{{ source_file  }}'
        dest : '{{ conf_file }}'
      notify : restart nginx

    - name   : create dir for tls
      file   : 
        path : /etc/nginx/certs
        state: directory
        mode : '0755' 

    - name   : copy tls key
      copy   : src=keys/https.key dest={{ tls_key_file }} owner=root mode=0600
      notify : restart nginx

    - name   : copy tls certificate
      copy   : src=keys/https.cert dest={{ tls_cert_file }} owner=root mode=0600
      notify : restart nginx

    - name   : copy index.html
      template:
        src  : templates/index.html.j2
        dest : /usr/share/nginx/html/index.html
        mode : 0644

    - name   : start nginx
      service:
        name : nginx
        state: started
        enabled: 1

  handlers   :
    - name   : restart nginx
      service: name=nginx state=restarted 
  roles:
    - nginx_on_centos
...
