#!/usr/bin/ansible-playbook --ask-vault-pass
---
- name: Configure web server with nginx
  hosts: wnodes
  become: yes
  
  vars_files:
    - ./group_vars/become_password

  vars:
    ansible_become_pass  : '{{ su_password }}'
    source_file          : ./templates/nginx-tls.conf.j2
    conf_file            : /etc/nginx/conf.d/https.conf
    tls_cert_file        : /etc/nginx/certs/https.cert
    tls_key_file         : /etc/nginx/certs/https.key

  tasks:
    - name   : install epel repo
      yum    : name=epel-release
    
    - name   : install nginx
      yum    : name=nginx update_cache=yes

    - name   : create conf.d directory
      file   :
        path : /etc/nginx/conf.d      
        state: directory
        mode : '0755' 
     
    - name   : copy nginx config file
      template: 
        src  : '{{ source_file  }}'
        dest : '{{ conf_file }}'
      notify : restart nginx

    - name   : create dir for tls
      file   : 
        path : /etc/nginx/certs
        state: directory
        mode : '0755' 
     
    - name   : copy tls key
      copy   : src=keys/https.key dest={{ tls_key_file }} owner=root mode=0600
      notify : restart nginx
    
    - name   : copy tls certificate
      copy   : src=keys/https.cert dest={{ tls_cert_file }} owner=root mode=0600
      notify : restart nginx

    - name   : copy index.html
      template:
        src  : templates/index.html.j2
        dest : /usr/share/nginx/html/index.html
        mode : 0644
   
    - name   : start nginx
      service:
        name : nginx
        state: started
        enabled: 1

  handlers   :
    - name   : restart nginx
      service: name=nginx state=restarted 
...

