#!/usr/bin/ansible-playbook --ask-vault-pass
---
- name: Configure web server with nginx
  hosts: wnodes
  become: yes
  
  vars_files:
    - ./group_vars/become_password

  vars:
    source_file : ./templates/nginx.conf
    conf_file : /etc/nginx/conf.d/http.conf
 
  tasks:
    - name   : install epel repo
      yum    : name=epel-release
    
    - name   : install nginx
      yum    : name=nginx update_cache=yes

    - name   : create conf.d directory
      file   :
        path : /etc/nginx/conf.d
        state: directory
        mode : '0755'

    - name   : copy nginx config file
      copy: 
        src  : '{{ source_file  }}'
        dest : '{{ conf_file }}'

    - name   : copy index.html
      template:
        src  : templates/index.html.j2
        dest : /usr/share/nginx/html/index.html
        mode : 0644
   
    - name   : start nginx
      service:
        name : nginx
        state: started
        enabled: 1

  handlers:
    - name   : restart nginx
      service: name=nginx state=restarted 
...

