#!/usr/bin/ansible-playbook --ask-vault-pass
---
- name: Configure web server with nginx
  hosts: wnodes
  become: yes
  
  vars_files:
    - ./group_vars/become_password

  roles:
    - nginx_on_centos
...
